### ISSUE TITLE
custom locale tab

### ISSUE THREAD

**Issue by cjuhong** [a2lix/TranslationFormBundle#171]
Hi,

How can I custom locale tab?
en  -->  English,

Fr -->  Francais

zh --> 中文

**Comment by webda2l** [comment]
Hi,

Quickest way is to override https://github.com/a2lix/TranslationFormBundle/blob/master/Resources/views/default.html.twig by a custom one, as http://a2lix.fr/bundles/translation-form/#bundle-configuration allow you.
And change L10 to read an associative array.

Otherwise, need more reflexion for a PR. (maybe add configuration to possibly use an Twig extension that automatically translate locale code in locale name   http://symfony.com/doc/current/components/intl.html#accessing-icu-data)

**Comment by lemoinem** [comment]
AFAIK, This was solved by #231
