### ISSUE TITLE
Branch 3.x and Gedmo 2.4.x

### ISSUE THREAD

**Issue by marcobarcaro** [a2lix/TranslationFormBundle#184]
Hi,
I don't understand from provided documentation if branch 3.x is compatible or not with Gedmo 2.4.x.

**Comment by webda2l** [comment]
Hi,

Initial plan about Gedmo was:

- let branch 1.x die, because based on the old implementation Gedmo Translation code (not very good...)
- branch 2.x would have been compatible with differents new implementations Translations (Knp, A2lix, ..), including the Gedmo new one https://github.com/Atlantic18/DoctrineExtensions/pull/764 whose name was 2.4 at first (before become 3.x)

Now, plan change about Gedmo.
Their version 2.4 is not a rewrite, and has always the same old Gedmo Translation code... Plan for better code seems abandonned.

So, current plan:

- always let branch 1.x die
- branch 2.x that stays SF2.3 will slowly die. And not compatible with 2.4 yes..
- branch 3.x will be the new master, compatible with >2.7 & 3.0. And if I thinking add again compatibility with current Gedmo 2.4, I don't think do it because I always dislike its implementation and prefer that people use another strategy like Knp one, or that the Gedmo 3.0 reborn...

**Comment by marcobarcaro** [comment]
Thanks for explanation, now it is much clear to me.
