### ISSUE TITLE
PHPCR-ODM ?

### ISSUE THREAD

**Issue by ibasaw** [a2lix/TranslationFormBundle#236]
hi,

how to use this bunlde with a PHPCR-ODM document ?

**Comment by jordisala1991** [comment]
Gedmo: https://github.com/Atlantic18/DoctrineExtensions/issues/1203
Knp: https://github.com/KnpLabs/DoctrineBehaviors/tree/master/src/ORM
Prezent: https://github.com/Prezent/doctrine-translatable-bundle/search?utf8=%E2%9C%93&q=phpcr&type=
A2lix: https://github.com/a2lix/I18nDoctrineBundle/search?utf8=%E2%9C%93&q=phpcr&type=

Since we rely on those 4, and none on them seems to support PHPCR-ODM, I guess you can't atm.

Closing this issue.

I guess first some of them should support it, before it makes sense to add it here. If you still think this is an issue for this bundle, please ping me to reopen
