### ISSUE TITLE
Render form fields for each translatable field separately

### ISSUE THREAD

**Issue by nilsabegg** [a2lix/TranslationFormBundle#67]
Hey,
this is not a bug report, it's a more like a support request.

I have a LocationTranslation entity with the properties "name" and "city". And I have a Location entity with other properties like zip, street, etc. 
In my from I would like to achieve the following order for the fields:

Name Translations
Street
Zip Code
City Translations
Can I build a form like that with the TranslationFormBundle?
Thanks in advance for any help or hint. ;)

Nils

**Comment by anacicconi** [comment]
Hi @webda2l, I tried the macros and they work great. However, I prefer to create my own template and override the default on the config because I need to add more info for my javascript to work. I wanted to know if it is possible to have more than one template for A2lix. For instance, I want to have a render on the backoffice and a different render on the frontoffice. In this case, where should I define them? Thanks ;)

**Comment by webda2l** [comment]
Hi @anacicconi, not it's not possible to have more than one template currently.
With http://symfony.com/doc/current/cookbook/form/form_customization.html#how-to-customize-an-individual-field you should do want you want.

**Comment by anacicconi** [comment]
Thanks @webda2l ! I think I found a way to display with macro without having to change the template.
